### ISSUE TITLE
cmake build does not generate correct configuration for visual studio

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#213]
When I build Herbert using 
`.\build.ps1 -build -matlab_release R2019b`

it generates visual studio project. If one attempts to execute tests from the visual studio, setting 
cpp_communicator.tests as the primary project, 
range of error is thrown. 
1) The gtests are not available in debug version, while the project refers to the gtests libraries in Debug folder. Changing this 
manually in cpp_communicator.test->properties->Linker->input->..\..\..\..\lib\Debug\gtest_maind.lib
to Release helps, but it is clear error in the configuration.

2) Attempt to run tests from visual studio ends up with error: 
![image](https://user-images.githubusercontent.com/1109606/89417051-13415800-d726-11ea-8edc-ecea59f364fd.png)

this is because the environment in properties->Debugger->Environment  is empty. 
Setting it to 
PATH=c:\programming\Matlab2019b64\bin\win64;$(PATH);
$(LocalDebuggerEnvironment)
fixes the issue, but it is clear some omission in the configuration. 
3) It is possible that target dll folder needs to be added to search path as well (have not yet tried)

**Comment by hsautessella** [comment]
Yes, you'll need to add `<Matlab Install Dir>/bin/win64` to your path either in Visual Studio, or before you launch it, in order to run the tests.

CTest adds the required path for you, which is why you can run the tests from the command line. 

I haven't found a straightforward way of getting CMake to specify runtime environment variables on Visual Studio targets (I suspect there isn't one). For now, we'll have to live with launching Visual Studio with the Matlab DLL directory on the path

**Comment by hsautessella** [comment]
I'll raise a ticket for an SMG on running/debugging tests - I probably should have written one before.

**Comment by abuts** [comment]
that's to our previous conversation on issues with VS project files. I have a feeling, (not entirely sure) that some time ago cmake have generated correct debugging environment. 

Anyway, its low priority ticket.

**Comment by hsautessella** [comment]
A possible solution is to manually generate a `.props` file, as described [here](https://gitlab.kitware.com/cmake/cmake/-/issues/8884), using CMake's `configure_file`.
